### ISSUE TITLE
使用自己的数据集出现问题

### ISSUE THREAD

**Issue by 670619720** [649453932/Chinese-Text-Classification-Pytorch#102]
Loading data...
Vocab size: 4762
491it [00:00, 98460.66it/s]
40it [00:00, ?it/s]
42it [00:00, 42113.50it/s]
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\Chinese-Text-Classification-Pytorch-master\run.py", line 41, in <module>
    dev_iter = build_iterator(dev_data, config)
  File "C:\Users\dell\Desktop\Chinese-Text-Classification-Pytorch-master\utils.py", line 117, in build_iterator
    iter = DatasetIterater(dataset, config.batch_size, config.device)
  File "C:\Users\dell\Desktop\Chinese-Text-Classification-Pytorch-master\utils.py", line 77, in __init__
    if len(batches) % self.n_batches != 0:
ZeroDivisionError: integer division or modulo by zero

**Comment by LMR-up** [comment]
batch改小一点12？

**Comment by lkq111** [comment]
改小batch，设为64可用。
