### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by leoxu1007** [649453932/Chinese-Text-Classification-Pytorch#79]
我换上了自己的语料库，就出现这个错误了

> Loading data...
> 578it [00:00, 88400.95it/s]
> Vocab size: 794
> 578it [00:00, 62273.51it/s]
> 33it [00:00, 48599.73it/s]
> 33it [00:00, 45056.00it/s]
> Traceback (most recent call last):
>   File "/home/Xu_Zhenyu/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "/home/Xu_Zhenyu/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "//tmp/Chinese-Text-Classification-Pytorch/run.py", line 41, in <module>
>     dev_iter = build_iterator(dev_data, config)
>   File "/tmp/Chinese-Text-Classification-Pytorch/utils.py", line 117, in build_iterator
>     iter = DatasetIterater(dataset, config.batch_size, config.device)
>   File "/tmp/Chinese-Text-Classification-Pytorch/utils.py", line 77, in __init__
>     if len(batches) % self.n_batches != 0:
> ZeroDivisionError: integer division or modulo by zero
> python-BaseException

**Comment by 9IrisSun** [comment]
你好，我也遇到了这个问题，请问你解决了吗
